### ISSUE TITLE
Metamask stack dump when adding liquidity

### ISSUE THREAD

**Issue by joelgriffiths** [DoppleFinance/dopple-contract#1]
Not sure if this is a problem with the contract or something else, but I'm getting this error when I try to add liquidity.

Error: This method only supports 0x-prefixed hex strings but input was: Https://dopple.finance
  at Object.r.assertIsHexString (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:72:210305)
  at Object.r.toChecksumAddress (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:72:201511)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:653574)
  at h.render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:478592)
  at Ya (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:70734)
  at Ka (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:70529)
  at jl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:105704)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:90053)
  at pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:89978)
  at iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87326)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45768
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:172:3472)
  at Vo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45477)
  at Yo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45713)
  at Ko (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45648)
  at au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87618)
  at Object.notify (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:24588)
  at e.t.notifyNestedSubs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:24155)
  at e.t.handleChangeWrapper (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:24223)
  at b (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:63254)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:57230
  at dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:59495)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:1350479
  at s.handleResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:4332)
  at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:21106)
  at s.i.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:24092)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18447)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18262)
  at s.y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:19073)
  at t.exports._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:113:216469)
  at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:31429)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:34607
  at t.exports.v.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:34634)
  at t.exports.m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:23642)
  at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:21106)
  at t.exports.i.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:24092)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18447)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18262)
  at t.exports.y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:19073)
  at t.exports._onMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:81:57176)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:81:57026

**Comment by joelgriffiths** [comment]
Rolling back to metamask 9.4.0 fixed the issue for me. Current version is 9.5.0.

**Comment by joelgriffiths** [comment]
Other people are experiencing this issue in the Dopple Finance Community Telegram channel as well.

**Comment by joelgriffiths** [comment]
This might be relevant:
https://ethereum.stackexchange.com/questions/98738/metamask-9-5-0-has-bug-when-transferring-to-my-other-account-on-test-network

**Comment by joelgriffiths** [comment]
This is starting to look like a metamask bug, not a contact bug. They updated the Issue I opened for the wallet.

**Comment by DoppleFinance** [comment]
Hi Joel,

Thanks for the updates!

Ben

**Comment by joelgriffiths** [comment]
Going to close this. It has nothing to do with the contract, and the Metamask people merged the fix into 9.5.1.
